### ISSUE TITLE
Grimoire questions

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/clj-docs#1]
- Building docs from jar vs src — what are the tradeoffs?
- Are there any fundamental issues with grimoire that could become problematic later?
- How do you build docs for a `[prj v]` when another version is already on the classpath? (e.g. grimoire itself)

**Comment by arrdem** [comment]
1. Jar vs source doesn't really matter as long as the source `.clj` or `.cljc` files haven't been stripped. It's just a Java classpath, as long as Clojure doesn't care lein-grim or your adaptation thereof shouldn't.
2. As discussed the Thing hierarchy needs some work.
3. You can't, without using boot pods or some other classpath isolation mechanism. The best strategy here is probably to just sub-JVM out with the dependencies you want and inject some minimal anonymized analysis code to that process. I suggest that sub-JVMs is probably the most general and reliable approach here, because boot pods can't isolate you against the packages already on the parent's classpath.

**Comment by martinklepsch** [comment]
> I suggest that sub-JVMs is probably the most general and reliable approach here, because boot pods can't isolate you against the packages already on the parent's classpath.

Not sure what you refer to as parent classpath but dependencies in pods are isolated from the code/classpath controlling the pod. That said we will still have at least stuff like codox, tools namespace etc alongside the to be analyzed dependency and those will need to be anonymized beforehand.
